export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const FETCH_VIDEO = 'FETCH_VIDEO';
export const FILTER_VIDEOS = 'FILTER_VIDEOS';
export const BOOKMARK = 'BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
